name: qgrid-environment
channels:
  -conda-forge
  -defaults
dependencies:
  -advertools
  -bs4
  -kmodes
  -lightgbm
  -matplotlib
  -numpy
  -pandas
  -plotnine
  -qgrid
  -seaborn
  -shap
  -sklearn
  -umap
  -voila
