name: qgrid-environment
channels:
  -conda-forge
  -defaults
dependencies:
  -advertools>=0.11.1
  -bs4>=0.0.1
  -kmodes>=0.11.0
  -lightgbm>=3.2.1
  -matplotlib>=3.3.4
  -numpy>=1.20.1
  -pandas>=1.2.4
  -plotnine>=0.8.0
  -qgrid>=1.3.1
  -seaborn>=0.11.1
  -shap>=0.39.0
  -sklearn
  -umap>=0.1.1
  -voila
