channels:
  - conda-forge
dependencies:
  - voila=0.2.10
  - pandas==1.2.4
  - numpy==1.20.1
  - matplotlib==3.3.4
  - seaborn==0.11.1
  - lightgbm==3.2.1
  - shap==0.39.0
  - scikit-learn==0.24.1
  - qgrid==1.3.1
